development:
  strategy: oauth
  oauth_consumer_key: PzCKLRYqLYY5JVuJJ1OI5w
  oauth_consumer_secret: KQOaifhJ32hz8UQH237Oo5GiXXJJrZNagZBkZLHnulM
  base_url: "https://twitter.com"
  authorize_path: "/oauth/authenticate"
  api_timeout: 10
  remember_for: 14 # days
  oauth_callback: "http://localhost:3000/oauth_callback"
test:
  strategy: oauth
  oauth_consumer_key: PzCKLRYqLYY5JVuJJ1OI5w
  oauth_consumer_secret: KQOaifhJ32hz8UQH237Oo5GiXXJJrZNagZBkZLHnulM
  base_url: "https://twitter.com"
  authorize_path: "/oauth/authenticate"
  api_timeout: 10
  remember_for: 14 # days
  oauth_callback: "http://localhost:3000/oauth_callback"
production:
  strategy: oauth
  oauth_consumer_key: PzCKLRYqLYY5JVuJJ1OI5w
  oauth_consumer_secret: KQOaifhJ32hz8UQH237Oo5GiXXJJrZNagZBkZLHnulM
  authorize_path: "/oauth/authenticate"
  base_url: "https://twitter.com"
  api_timeout: 10
  remember_for: 14 # days

